spring.application.name=sistem-donasi
# Menggunakan environment variable dari Docker, jika tidak ada akan default ke localhost
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_donasi_banjir}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pbo_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pbo_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect